### ISSUE TITLE
Enable nice website previews in social media

### ISSUE THREAD

**Issue by simondorfman** [ETHChicago/ethchi-website#14]
**Why make this change? (user story)**
As a volunteer ETHChicago marketer
I want to see nice website previews when I post our website in discord (and other socials, e.g. telegram)
So that people are more likely to click the link and learn about our event.

**How do we do it?**
I haven't done this before, but it looks like we need some Open Graph meta tags, according to this post:
https://web-highlights.com/blog/turn-your-website-into-a-beautiful-thumbnail-link-preview/

**What content should be in the preview?**
1. ETH CHI logo
2. September 15-17, 2023
3. Location: [The M Club](https://www.invitedclubs.com/clubs/the-metropolitan) - Willis Tower, [233 S Wacker Dr, Chicago, IL 60606](https://www.google.com/maps/place/233+S+Wacker+Dr,+Chicago,+IL+60606/)
Floor: 66 & 67
4. Hackathon, Conference, Side Events

**Example screenshot from Discord**
<img src="https://github.com/ETHChicago/ethchi-website/assets/106923/a731daad-8970-4e6b-8270-ad6d7da0c461" alt="discord screenshot" width="300"/>

**Comment by trbutler4** [comment]
implemented on dev
