### ISSUE TITLE
Add Holoplex to Website 

### ISSUE THREAD

**Issue by rrachfor** [ETHChicago/ethchi-website#17]
Please add whichever of the attached logos looks best on the site.  Thanks, Thomas! 
![Wordmark - White](https://github.com/ETHChicago/ethchi-website/assets/101080298/4ce34ebf-c8a9-403e-8565-83be201e89a7)
![Wordmark - Dark](https://github.com/ETHChicago/ethchi-website/assets/101080298/07b1c8ac-6ff4-41b8-b6c9-da294489a4e4)

**Comment by trbutler4** [comment]
done
