### ISSUE TITLE
Remove the number of tickets that are still available from the Unlock page 

### ISSUE THREAD

**Issue by rrachfor** [ETHChicago/ethchi-website#18]
Hey Hey,

Currently the unlock page shows how many tickets are left - this allows users to do some back calculation to see that only a handful of tickets have been sold so far. 
![image](https://github.com/ETHChicago/ethchi-website/assets/101080298/9754d64e-876d-46e2-8936-3be68f99a930)

Can you please remove this feature? 

Thanks!

**Comment by trbutler4** [comment]
reached out to patrick workman (unlock guy) on this

**Comment by trbutler4** [comment]
updated tickets to be unlimited, will monitor them and change the checkout link when needed
