### ISSUE TITLE
Add hyperlink to forum in FAQ text

### ISSUE THREAD

**Issue by simondorfman** [ETHChicago/ethchi-website#26]
**Current state:**
HOW CAN I PARTICIPATE IN ETHCHICAGO?
There are several ways you can participate in ETHChicago: as a volunteer, partner, speaker, mentor, or attendee. Our website is a great starting point but also feel free to checkout forum.ethchicago.xyz or contact us directly on [Twitter](https://twitter.com/0xEthChicago) & [ecosystem@ethchicago.xyz](mailto:ecosystem@ethchicago.xyz)

**Future State:**
HOW CAN I PARTICIPATE IN ETHCHICAGO?
There are several ways you can participate in ETHChicago: as a volunteer, partner, speaker, mentor, or attendee. Our website is a great starting point but also feel free to checkout [forum.ethchicago.xyz](https://forum.ethchicago.xyz) or contact us directly on [Twitter](https://twitter.com/0xEthChicago) & [ecosystem@ethchicago.xyz](mailto:ecosystem@ethchicago.xyz)

**Comment by trbutler4** [comment]
done
