### ISSUE TITLE
Adding more sponsors to website

### ISSUE THREAD

**Issue by james-prysm** [ETHChicago/ethchi-website#28]
- ethereum support program
- taikai
- CMT Digital
- Formidium Corp.
- Ledgible

may need things a lot smaller for more to come.

**Comment by trbutler4** [comment]
do you have the logos they want?

**Comment by james-prysm** [comment]
https://drive.google.com/drive/u/2/folders/1booSd5VfWJakqJhiCOiiC8QvqxRZZjrg for ethereum support program. I assume you can take it from the website if they didn't send to us explicitly

**Comment by trbutler4** [comment]
added to dev
