### ISSUE TITLE
Create form to accept hacker applications

### ISSUE THREAD

**Issue by simondorfman** [ETHChicago/ethchi-website#3]

**Comment by simondorfman** [comment]
James working on this.

After hacker submits form, have a link to buy the ticket. @trbutler4 to supply Unlock URL to be added here.

We're focusing on the happy path for ticketing. We're not worrying too much about hackers sharing the direct link to the Unlock URL. We'll have to deal with that if it happens.

@trbutler4, will Unlock require an email address? We need a way to be able to tie the Unlock NFT back to the Google Form hacker.

**Comment by trbutler4** [comment]
after ticket purchase, we get to specify the redirect url. Maybe send them to a form to enter their info there?

**Comment by simondorfman** [comment]
> after ticket purchase, we get to specify the redirect url. Maybe send them to a form to enter their info there?

Oh, good to know that Unlock lets you pick a redirect URL. We (James and I) were thinking the user flow would be:
1. fill out registration form; if you choose the buy now option (as opposed to waiting and hoping someone will sponsor your ticket) send to Unlock URL
2. buy ticket on Unlock
3. (now that we know you can set up redirect at end, I'm thinking step 3 is...) send user to Devpost (if it's possible to automatically whitelist the user with Devpost as part of this process)

**Comment by trbutler4** [comment]
this is done
