### ISSUE TITLE
Capitalize attend button text

### ISSUE THREAD

**Issue by adrian-petrykiw** [ETHChicago/ethchi-website#39]
<img width="1440" alt="image" src="https://github.com/ETHChicago/ethchi-website/assets/49378232/4c3053ce-d2f8-4dcb-822a-62d8bbba5a79">

**Comment by OokamiKitsune** [comment]
@adrian-petrykiw Unless someone was working on this, I have a branch that updated this. I cannot push it as I don't have permission.
