### ISSUE TITLE
Update Notion document with high level hackathon information

### ISSUE THREAD

**Issue by james-prysm** [ETHChicago/ethchi-website#5]
update
https://chicagodao.notion.site/ETH-Chicago-Hackathon-2328d3c64c6f4555b8b4dae856b1c999

with 

https://forum.ethchicago.xyz/t/hackathon-structure/15

**Comment by james-prysm** [comment]
updated, please review @simondorfman

**Comment by simondorfman** [comment]
looks good, closing
